sonata_block:
    default_contexts: [cms]
    blocks:

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
            
sonata_admin:
    title:      RGV Labs
    # title_logo: bundles/app/images/fancy_acme_logo.png            

